### ISSUE TITLE
teehistorian2demo: thread 'main' panicked at 'assertion failed: 0 <= self.client_id && self.client_id <= MAX_CLIENTS - 1', gamenet/src/snap_obj.rs:938:9

### ISSUE THREAD

**Issue by def-** [heinrich5991/libtw2#35]
```
$ RUST_BACKTRACE=full /media/libtw2/target/debug/teehistorian2demo 7482cb75-d198-4256-b80d-c69f342c95ff.teehistorian
thread 'main' panicked at 'assertion failed: 0 <= self.client_id && self.client_id <= MAX_CLIENTS - 1', gamenet/src/snap_obj.rs:938:9
stack backtrace:
   0:     0x55ee7c3dc360 - std::backtrace_rs::backtrace::libunwind::trace::ha31cb35ba35052ca
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55ee7c3dc360 - std::backtrace_rs::backtrace::trace_unsynchronized::h914154c46fedb791
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55ee7c3dc360 - std::sys_common::backtrace::_print_fmt::h4bed7544cf4783cc
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:79
   3:     0x55ee7c3dc360 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h71baf994de642464
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:58
   4:     0x55ee7c3fb7ec - core::fmt::write::hcb5569f97eae5185
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/fmt/mod.rs:1082
   5:     0x55ee7c3da007 - std::io::Write::write_fmt::hec04380539c975a7
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/io/mod.rs:1514
   6:     0x55ee7c3de570 - std::sys_common::backtrace::_print::h7217f428d769d34f
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:61
   7:     0x55ee7c3de570 - std::sys_common::backtrace::print::heb9b7db110cef504
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:48
   8:     0x55ee7c3de570 - std::panicking::default_hook::{{closure}}::hc8bd48d88d5fcceb
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:200
   9:     0x55ee7c3de2bc - std::panicking::default_hook::h4a7994bce6af5114
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:219
  10:     0x55ee7c3debd3 - std::panicking::rust_panic_with_hook::h796dceade986353b
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:569
  11:     0x55ee7c286a8c - std::panicking::begin_panic::{{closure}}::h416179a7af2fee40
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:498
  12:     0x55ee7c2886c9 - std::sys_common::backtrace::__rust_end_short_backtrace::h1b903db681673098
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:153
  13:     0x55ee7c2869b7 - std::panicking::begin_panic::h33ac19220b99d72e
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:497
  14:     0x55ee7c27018e - gamenet::snap_obj::PlayerInfo::encode::h3eec30657d2d633e
                               at /media/libtw2/gamenet/src/snap_obj.rs:938
  15:     0x55ee7c1190c7 - teehistorian2demo::process::h4ca4ace54434f115
                               at /media/libtw2/tools/src/bin/teehistorian2demo.rs:200
  16:     0x55ee7c11a400 - teehistorian2demo::main::h9cbf2c5663608aa6
                               at /media/libtw2/tools/src/bin/teehistorian2demo.rs:277
  17:     0x55ee7c11558b - core::ops::function::FnOnce::call_once::h3aa9dde62d42bf95
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/ops/function.rs:227
  18:     0x55ee7c10439e - std::sys_common::backtrace::__rust_begin_short_backtrace::hd0b21bdb1d841623
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:137
  19:     0x55ee7c114311 - std::rt::lang_start::{{closure}}::hc905b80db833b0ac
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/rt.rs:66
  20:     0x55ee7c3defbe - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b46348dde94a3ab
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/ops/function.rs:259
  21:     0x55ee7c3defbe - std::panicking::try::do_call::h65a06556d74549bf
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:373
  22:     0x55ee7c3defbe - std::panicking::try::h906dbc9901f62921
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:337
  23:     0x55ee7c3defbe - std::panic::catch_unwind::hd56632d711be2855
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panic.rs:379
  24:     0x55ee7c3defbe - std::rt::lang_start_internal::h90f188c8b72672f1
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/rt.rs:51
  25:     0x55ee7c1142e7 - std::rt::lang_start::h9e33b6276f9c20b0
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/rt.rs:65
  26:     0x55ee7c11a77a - main
  27:     0x7ff09dad6152 - __libc_start_main
  28:     0x55ee7c10409e - _start
  29:                0x0 - <unknown>
```
from GER1

**Comment by heinrich5991** [comment]
Workaround: Set `MAX_CLIENTS` in gamenet/src/enums.rs to 64.

```rust
pub const MAX_CLIENTS: i32 = 64;
```

**Comment by def-** [comment]
When I set that workaround some demos still fail: 4a5667e5-bfdd-45f1-a4f7-9850d789b49d

```
thread 'main' panicked at 'key not present', tools/src/bin/teehistorian2demo.rs:147:33
stack backtrace:
   0: rust_begin_unwind
             at /build/rust/src/rustc-1.48.0-src/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /build/rust/src/rustc-1.48.0-src/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /build/rust/src/rustc-1.48.0-src/library/core/src/option.rs:1226
   3: teehistorian2demo::main
```

**Comment by heinrich5991** [comment]
That other problem ("key not present") is missing 0.7 support (#30), which takes more effort to fix, I don't know a workaround.
